CREATE DATABASE primes_db;
USE prime_db;

CREATE TABLE primes (id INT AUTO_INCREMENT PRIMARY KEY, 
prime_number INT NOT NULL UNIQUE, 
prime_number_code INT NOT NULL UNIQUE, 
ascii VARCHAR(255) CHARACTER SET utf8mb4);
)
